// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjlwzvZ1GJbf6u6bmh17s7ON0FIUY1Kc8',
    appId: '1:596264920314:web:e018ee90fdcbcdb763d543',
    messagingSenderId: '596264920314',
    projectId: 'store101-19bc4',
    authDomain: 'store101-19bc4.firebaseapp.com',
    storageBucket: 'store101-19bc4.appspot.com',
    measurementId: 'G-012QMZ3GP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFaPkqQxdXdzSXXeTzBQLB6UAtoObym_A',
    appId: '1:596264920314:android:6191bd901e106b3863d543',
    messagingSenderId: '596264920314',
    projectId: 'store101-19bc4',
    storageBucket: 'store101-19bc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOQaVIJhmHY6ZH3aj6UdMQglDM9SmQ-s',
    appId: '1:596264920314:ios:3a269d0c9caf4f1263d543',
    messagingSenderId: '596264920314',
    projectId: 'store101-19bc4',
    storageBucket: 'store101-19bc4.appspot.com',
    iosBundleId: 'com.example.estore',
  );
}
